#!/usr/bin/env bash
# Regenerate cloudflare-ips.conf from Cloudflare's published ranges.
# Keeps the committed file when the download fails or looks wrong, so a
# Cloudflare/network hiccup never produces an empty allowlist.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TARGET="$SCRIPT_DIR/cloudflare-ips.conf"
CIDR_RE='^[0-9a-fA-F:.]+/[0-9]{1,3}$'

fetch() { curl -fsS --max-time 15 "$1" | tr -d '\r' | grep -E "$CIDR_RE"; }

if ! v4="$(fetch https://www.cloudflare.com/ips-v4)" || ! v6="$(fetch https://www.cloudflare.com/ips-v6)"; then
  echo "cloudflare-ips: download failed — keeping committed $TARGET" >&2
  exit 0
fi
ranges="$(printf '%s\n%s\n' "$v4" "$v6")"
if [[ "$(wc -l <<<"$ranges")" -lt 10 ]]; then
  echo "cloudflare-ips: suspiciously short list — keeping committed $TARGET" >&2
  exit 0
fi

tmp="$(mktemp "$TARGET.XXXXXX")"
{
  echo "# Generated by update-cloudflare-ips.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ). Do not edit by hand."
  echo "# Included at http level. Real client IP from CF-Connecting-IP, trusted only"
  echo "# from Cloudflare's edge; \$from_cloudflare flags requests whose TCP peer is Cloudflare."
  while read -r cidr; do echo "set_real_ip_from $cidr;"; done <<<"$ranges"
  echo "real_ip_header CF-Connecting-IP;"
  echo ""
  echo "geo \$realip_remote_addr \$from_cloudflare {"
  echo "    default 0;"
  while read -r cidr; do echo "    $cidr 1;"; done <<<"$ranges"
  echo "}"
} >"$tmp"
chmod 644 "$tmp"
mv "$tmp" "$TARGET"
echo "cloudflare-ips: updated $TARGET ($(wc -l <<<"$ranges") ranges)"
