#!/bin/bash
set -euo pipefail

# Regenerate cloudflare-ips.include from Cloudflare's published IP lists.
#
# nginx-docker.conf includes this file to restore each visitor's real IP
# (set_real_ip_from + CF-Connecting-IP) so per-IP rate limiting keys on the
# visitor, not on a Cloudflare edge. Cloudflare updates their ranges a few
# times a year; a hand-copied list silently rots and every bucket becomes
# shared again. This script fetches the current list from the source of truth
# and writes one `set_real_ip_from <range>;` directive per line.
#
# Run by deploy-scaleway.sh before the stack comes up; safe to run manually:
#   bash deployment/update-cloudflare-ips.sh
#
# Keeps the last known-good file on network failure: without it nginx would
# refuse to start on a config with zero trusted ranges (or, worse, keep
# proxying with stale trust) — a deploy must not hinge on Cloudflare being up.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUTPUT_FILE="$SCRIPT_DIR/cloudflare-ips.include"

IPV4_URL="https://www.cloudflare.com/ips-v4"
IPV6_URL="https://www.cloudflare.com/ips-v6"

TMP_FILE="$(mktemp)"
trap 'rm -f "$TMP_FILE"' EXIT

# shellcheck disable=SC1090
fetch() {
  # One retry, then give up and keep the previous file — a stale list is
  # strictly better than no list.
  curl --fail --silent --show-error --max-time 30 --retry 1 "$1"
}

echo "Fetching Cloudflare IP ranges..."
# `printf '\n'` between the two fetches: ips-v4 ships without a trailing
# newline, so without it the first IPv6 range would be glued onto the last
# IPv4 range (`131.0.72.0/222400:cb00::/32`) and fail the CIDR check.
fetch "$IPV4_URL" > "$TMP_FILE" || { echo "Failed to fetch $IPV4_URL — keeping existing $OUTPUT_FILE" >&2; exit 0; }
printf '\n' >> "$TMP_FILE"
fetch "$IPV6_URL" >> "$TMP_FILE" || { echo "Failed to fetch $IPV6_URL — keeping existing $OUTPUT_FILE" >&2; exit 0; }

# Sanity check: a plausible list has dozens of ranges and every line is an
# IPv4/IPv6 CIDR. An HTML error page would pass neither test.
RANGE_PATTERN='^([0-9]{1,3}\.){3}[0-9]{1,3}/[0-9]{1,2}$|^[0-9a-fA-F:]+/[0-9]{1,3}$'
BAD_LINES=$(grep -Evc "$RANGE_PATTERN" "$TMP_FILE" || true)
if [ "$(wc -l < "$TMP_FILE")" -lt 10 ] || [ "$BAD_LINES" -ne 0 ]; then
  echo "Fetched list looks malformed ($(wc -l < "$TMP_FILE") lines, $BAD_LINES non-CIDR) — keeping existing $OUTPUT_FILE" >&2
  exit 0
fi

{
  echo "# Generated by update-cloudflare-ips.sh from $IPV4_URL and $IPV6_URL."
  echo "# Do not edit by hand — rerun the script instead. Last updated: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  sed 's/^/set_real_ip_from /; s/$/;/' "$TMP_FILE"
} > "$OUTPUT_FILE"

echo "Wrote $(grep -c set_real_ip_from "$OUTPUT_FILE") Cloudflare ranges to $OUTPUT_FILE"